// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: crud.proto

package crud

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Gender int32

const (
	Gender_Male   Gender = 0
	Gender_Female Gender = 1
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "Male",
		1: "Female",
	}
	Gender_value = map[string]int32{
		"Male":   0,
		"Female": 1,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_crud_proto_enumTypes[0].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_crud_proto_enumTypes[0]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_crud_proto_rawDescGZIP(), []int{0}
}

type Membership int32

const (
	Membership_Free    Membership = 0
	Membership_Premium Membership = 1
)

// Enum value maps for Membership.
var (
	Membership_name = map[int32]string{
		0: "Free",
		1: "Premium",
	}
	Membership_value = map[string]int32{
		"Free":    0,
		"Premium": 1,
	}
)

func (x Membership) Enum() *Membership {
	p := new(Membership)
	*p = x
	return p
}

func (x Membership) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Membership) Descriptor() protoreflect.EnumDescriptor {
	return file_crud_proto_enumTypes[1].Descriptor()
}

func (Membership) Type() protoreflect.EnumType {
	return &file_crud_proto_enumTypes[1]
}

func (x Membership) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Membership.Descriptor instead.
func (Membership) EnumDescriptor() ([]byte, []int) {
	return file_crud_proto_rawDescGZIP(), []int{1}
}

type Nil struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nil) Reset() {
	*x = Nil{}
	mi := &file_crud_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nil) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nil) ProtoMessage() {}

func (x *Nil) ProtoReflect() protoreflect.Message {
	mi := &file_crud_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nil.ProtoReflect.Descriptor instead.
func (*Nil) Descriptor() ([]byte, []int) {
	return file_crud_proto_rawDescGZIP(), []int{0}
}

type UserSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	EmpId         int32                  `protobuf:"varint,3,opt,name=emp_id,json=empId,proto3" json:"emp_id,omitempty"`
	Gender        Gender                 `protobuf:"varint,4,opt,name=gender,proto3,enum=crud.Gender" json:"gender,omitempty"`
	Premium       Membership             `protobuf:"varint,5,opt,name=premium,proto3,enum=crud.Membership" json:"premium,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSpec) Reset() {
	*x = UserSpec{}
	mi := &file_crud_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSpec) ProtoMessage() {}

func (x *UserSpec) ProtoReflect() protoreflect.Message {
	mi := &file_crud_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSpec.ProtoReflect.Descriptor instead.
func (*UserSpec) Descriptor() ([]byte, []int) {
	return file_crud_proto_rawDescGZIP(), []int{1}
}

func (x *UserSpec) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserSpec) GetEmpId() int32 {
	if x != nil {
		return x.EmpId
	}
	return 0
}

func (x *UserSpec) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_Male
}

func (x *UserSpec) GetPremium() Membership {
	if x != nil {
		return x.Premium
	}
	return Membership_Free
}

type Id struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Id) Reset() {
	*x = Id{}
	mi := &file_crud_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Id) ProtoMessage() {}

func (x *Id) ProtoReflect() protoreflect.Message {
	mi := &file_crud_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Id.ProtoReflect.Descriptor instead.
func (*Id) Descriptor() ([]byte, []int) {
	return file_crud_proto_rawDescGZIP(), []int{2}
}

func (x *Id) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_crud_proto protoreflect.FileDescriptor

const file_crud_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"crud.proto\x12\x04crud\"\x05\n" +
	"\x03Nil\"\x97\x01\n" +
	"\bUserSpec\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x15\n" +
	"\x06emp_id\x18\x03 \x01(\x05R\x05empId\x12$\n" +
	"\x06gender\x18\x04 \x01(\x0e2\f.crud.GenderR\x06gender\x12*\n" +
	"\apremium\x18\x05 \x01(\x0e2\x10.crud.MembershipR\apremium\"\x14\n" +
	"\x02Id\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id*\x1e\n" +
	"\x06Gender\x12\b\n" +
	"\x04Male\x10\x00\x12\n" +
	"\n" +
	"\x06Female\x10\x01*#\n" +
	"\n" +
	"Membership\x12\b\n" +
	"\x04Free\x10\x00\x12\v\n" +
	"\aPremium\x10\x012\xd1\x01\n" +
	"\vCrudService\x12#\n" +
	"\aGetUser\x12\b.crud.Id\x1a\x0e.crud.UserSpec\x12#\n" +
	"\aNewUser\x12\x0e.crud.UserSpec\x1a\b.crud.Id\x12&\n" +
	"\n" +
	"DeleteUser\x12\b.crud.Id\x1a\x0e.crud.UserSpec\x12)\n" +
	"\aSetUser\x12\x0e.crud.UserSpec\x1a\x0e.crud.UserSpec\x12%\n" +
	"\x06GetAll\x12\t.crud.Nil\x1a\x0e.crud.UserSpec0\x01B5Z3github.com/abhijeet-singh800/grpc-test/grpcPkg/crudb\x06proto3"

var (
	file_crud_proto_rawDescOnce sync.Once
	file_crud_proto_rawDescData []byte
)

func file_crud_proto_rawDescGZIP() []byte {
	file_crud_proto_rawDescOnce.Do(func() {
		file_crud_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_crud_proto_rawDesc), len(file_crud_proto_rawDesc)))
	})
	return file_crud_proto_rawDescData
}

var file_crud_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_crud_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_crud_proto_goTypes = []any{
	(Gender)(0),      // 0: crud.Gender
	(Membership)(0),  // 1: crud.Membership
	(*Nil)(nil),      // 2: crud.Nil
	(*UserSpec)(nil), // 3: crud.UserSpec
	(*Id)(nil),       // 4: crud.Id
}
var file_crud_proto_depIdxs = []int32{
	0, // 0: crud.UserSpec.gender:type_name -> crud.Gender
	1, // 1: crud.UserSpec.premium:type_name -> crud.Membership
	4, // 2: crud.CrudService.GetUser:input_type -> crud.Id
	3, // 3: crud.CrudService.NewUser:input_type -> crud.UserSpec
	4, // 4: crud.CrudService.DeleteUser:input_type -> crud.Id
	3, // 5: crud.CrudService.SetUser:input_type -> crud.UserSpec
	2, // 6: crud.CrudService.GetAll:input_type -> crud.Nil
	3, // 7: crud.CrudService.GetUser:output_type -> crud.UserSpec
	4, // 8: crud.CrudService.NewUser:output_type -> crud.Id
	3, // 9: crud.CrudService.DeleteUser:output_type -> crud.UserSpec
	3, // 10: crud.CrudService.SetUser:output_type -> crud.UserSpec
	3, // 11: crud.CrudService.GetAll:output_type -> crud.UserSpec
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_crud_proto_init() }
func file_crud_proto_init() {
	if File_crud_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crud_proto_rawDesc), len(file_crud_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_crud_proto_goTypes,
		DependencyIndexes: file_crud_proto_depIdxs,
		EnumInfos:         file_crud_proto_enumTypes,
		MessageInfos:      file_crud_proto_msgTypes,
	}.Build()
	File_crud_proto = out.File
	file_crud_proto_goTypes = nil
	file_crud_proto_depIdxs = nil
}
